# Generated by Django 5.0.1 on 2024-01-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_business_about_ru_business_about_zh_hans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('about', models.CharField(max_length=255, verbose_name='О деятельности')),
                ('about_ru', models.CharField(max_length=255, null=True, verbose_name='О деятельности')),
                ('about_zh_hans', models.CharField(max_length=255, null=True, verbose_name='О деятельности')),
                ('poster', models.ImageField(upload_to='main/business/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
        ),
    ]
