# Generated by Django 5.0.1 on 2024-01-06 04:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_offer_about_alter_offer_about_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='about_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='about_zh_hans',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
    ]
