# Generated by Django 5.0.1 on 2024-01-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_offer_about_alter_offer_about_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='about_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
    ]
