# Generated by Django 5.0.1 on 2024-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_offer_about_alter_offer_about_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='about_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='О деятельности'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='about_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='О деятельности'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
