# Generated by Django 5.0.1 on 2024-01-06 05:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_logistic_about_ru_logistic_about_zh_hans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description_zh_hans',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='about_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='О деятельности'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='description_zh_hans',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
